### ISSUE TITLE
Try a cubic hermite spline as the transition spline

### ISSUE THREAD

**Issue by Mike-Dax** [Scottapotamas/zaphod-bot#15]
I believe this gives us the ability to specify two points in position space and two vectors in derivative space, effectively letting us set the positions, exit and entry velocities, which is likely ideal for transitions.

Should also implement better global velocity visualisation in the toolpath viewer so we can visually verify velocity continuity between lines and transitions.

**Comment by Scottapotamas** [comment]
Spline 'linearisation' is achieved via interpolating against a distance vs _t_ LUT generated during the spline length calculation.

This approach was described in https://pomax.github.io/bezierinfo for beziers, but the implementation in firmware applies to other splines too!

Tests show consistent speed for most moves with no measurable performance impact.
